### PR TITLE
Keep consistency in object quotes

### PR DESCRIPTION
**Pull request by Joozty**

### CODE REVIEW

**Comment by viktor-yakubiv** [comment]
Did not [Prettier's option](https://prettier.io/docs/en/options.html#quote-props) work?

**Comment by Joozty** [comment]
I thought I needed to specify eslint rule together with prettier rule. It looks like eslint rule is redundant. Thanks

**Comment by viktor-yakubiv** [comment]
It is not only redundant. We use eslint-prettier-plugin to disable conflicting rules. It's recommended because it's possible to mix some ESLint config, e.g. Airbnb's, with prettier and some rules will conflict.

**Comment by Joozty** [comment]
Fair enough. Cam you approve then?

**Review by viktor-yakubiv — APPROVED** [review]

**Pull request merged**
